<?php


/**
 * Implements hook_block_info().
 */
function trekker_block_info() {
  $blocks['addToMyGear']['info'] = t('Add an item to your gear');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function trekker_block_view($delta='') {
    $block = array();
    switch($delta) {
        case 'addToMyGear' :
        $block['content'] = drupal_get_form('trekker_addToMyGear_form');
        break;
    }

    return $block;
}

function trekker_addToMyGear_form($form_state) {
    $form['nid'] = array(
        '#type' => 'hidden',
        '#value' => arg(1)
    );
    $form['button'] = array(
        '#type' => 'submit',
        //'#src' => file_create_url(drupal_get_path('module', 'trekker').'/process_add.png'),
        '#value' => t('Add to my gear'),
    );
    drupal_set_message(arg(1), 'status');
    return $form;
}

function trekker_addToMyGear_form_submit($form, &$form_state) {
    $nid = $form_state['values']['nid'];
    drupal_set_message('Please fill out form below to add item to your gear', 'status');
    $form_state['redirect'] = '/node/add/my-gear';
}